### ISSUE TITLE
Why not to patch the service instead of patching all the pods.

### ISSUE THREAD

**Issue by F1bonacc1** [psdally/k8s-active-passive#1]
Hi,

If you know the active pod name:
```shell
kubectl patch pod $active -p '{"metadata": {"labels": {"role":"passive"}}}';
```
Why not to patch the service:
```yaml
spec:
  selector:
    app.kubernetes.io/name: helloworld-statefulset
    statefulset.kubernetes.io/pod-name: $active  # <--- add pod name to selector
```

Then you won't have to change the state of the (previously) active pod to passive.
